import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <div className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <nav className="sticky top-0 flex items-center justify-between p-4 shadow backdrop-blur-sm">
              <Link href="/" className="flex items-center">
                <span className="text-lg font-bold text-white">
                  Create <span className="text-[hsl(280,100%,70%)]">T3</span>{" "}
                  App
                </span>
              </Link>
              <div className="flex items-center font-bold">
                <Link href="/">
                  <p className="mr-4 text-white">Home</p>
                </Link>
                <Link href="/dashboard">
                  <p className="text-white">Dashboard</p>
                </Link>
              </div>
            </nav>
            <main className="min-h-screen"> {children}</main>
            <footer className="sticky bottom-0 py-2 text-center text-white">
              This is the footer. © {new Date().getFullYear()} My App. All
              rights reserved.
            </footer>
          </div>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
